# hello-go task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go

outputs:
- name: hello-go-updated

run:
  path: ./hello-go/ci/scripts/readme-github-pages.sh
