# hello-go task-build.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: my-repo

outputs:
- name: dist

run:
  path: my-repo/ci/scripts/build
