# hello-go task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go

run:
  path: ./hello-go/ci/scripts/deploy.sh