################################################################################
# REFERENCES
# ConcourseCI Docs: https://concourse.ci
# Concourse tutorial: https://github.com/starkandwayne/concourse-tutorial
#
# NOTES
# This file is a self-contained description of a Concourse CI pipeline
# to deploy a http://gosparta.io application.  There's a couple of things to
# note:
#   - The YAML uses node references so that scripts can be defined in the
#     CONSTANTS key and referenced in the jobs section
#   - This requires an additional YML file that defines AWS credentials and the
#     S3 bucket that should be used for storage. Required keys:
#       s3-bucket: XXXXXX
#       s3-access-key-id: XXXXXXXXXXXXXXXXXX
#       s3-secret-access-key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

################################################################################
# RESOURCES
################################################################################
resources:
- name: simple-go-webapp-source
  type: git
  source:
    uri: https://github.com/tryggth/concourse-example
    paths: [app]

- name: simple-go-docker-source
  type: git
  source:
    uri: https://github.com/tryggth/concourse-example
    paths: [docker]

- name: app-version
  type: semver
  source:
    branch: version
    driver: git
    file: app-version
    initial_version: 0.0.1
    password: {{git-password}}
    uri: https://github.com/tryggth/concourse-example.git
    username: tryggth

- name: container-version
  type: semver
  source:
    branch: version
    driver: git
    file: version
    initial_version: 0.0.1
    password: {{git-password}}
    uri: https://github.com/tryggth/concourse-example.git
    username: tryggth

- name: SourceArchive
  type: gcs-resource
  source:
      bucket: concourse-demo
      json_key: {{gcs-storage}}
      regexp: simple-go-webapp-source-(.*).tgz

- name: BinaryArchive
  type: gcs-resource
  source:
      bucket: concourse-demo
      json_key: {{gcs-storage}}
      regexp: simple-go-webapp-app-(.*)

- name: simple-go-webapp-docker-image
  type: docker-image
  source:
    email: tryggth2009@gmail.com
    password: {{git-password}}
    repository: tryggth/simple-go-webapp
    username: tryggth

################################################################################
# JOBS
################################################################################
jobs:
  - name: Package
    serial_groups: [app-version]
    plan:
    - get: simple-go-webapp-source
      trigger: true
    - get: app-version
      params:
        bump: patch
    - task: package
      config:
        << : *CONFIG
        inputs:
          - name: simple-go-webapp-source
          - name: app-version
        run:
          path: sh
          args:
          - -exc
          - *PACKAGE_SCRIPT
        outputs:
          - name: build
    - put: SourceArchive
      params:
        file: build/simple-go-webapp-source-*.tgz*
    - put: app-version
      params:
        file: app-version/number

  - name: UnitTest
    plan:
    - get: SourceArchive
      passed: [Package]
      trigger: true
    - task: unit-test
      config:
        << : *CONFIG
        inputs:
          - name: SourceArchive
        run:
          path: sh
          args:
          - -exc
          - *UNIT_TEST_SCRIPT

  - name: Build
    plan:
    - get: SourceArchive
      passed: [UnitTest]
      trigger: true
    - get: app-version
    - task: build
      config:
        << : *CONFIG
        inputs:
          - name: app-version
          - name: SourceArchive
        run:
          path: bash
          args:
          - -exc
          - *BUILD_SCRIPT
        outputs:
        - name: build
    - put: BinaryArchive
      params:
        file: build/simple-go-webapp-app-*

  - name: BuildContainer
    serial: true
    plan:
    - get: container-version
      params:
        bump: patch
    - get: BinaryArchive
      passed: [Build]
      trigger: true
    - get: simple-go-docker-source
      trigger: true
    - task: build-container
      config:
        << : *CONFIG
        inputs:
          - name: simple-go-docker-source
          - name: BinaryArchive
        run:
          path: sh
          args:
          - -exc
          - *DOCKER_SETUP_SCRIPT
        outputs:
          - name: dockerbuild
    - put: simple-go-webapp-docker-image
      params:
        build: dockerbuild
        tag: container-version/number
    - put: container-version
      params:
        file: container-version/number

################################################################################
# CONSTANTS
################################################################################
CONSTANTS:
  - CONFIG: &CONFIG
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: '1.7'
  - PACKAGE_SCRIPT: &PACKAGE_SCRIPT |
        cd app-version
          SEM_NUMBER=`cat number`
          SEM_VERSION=`cat version`
          echo "SEM_NUMBER=$SEM_NUMBER, SEM_VERSION=$SEM_VERSION"
        cd ..

        cd simple-go-webapp-source
          if [ ! -d ./vendor ]
            then
              echo "./vendor does not exist - fetching packages"
              go get -d -v ./...
              ls -la $GOPATH/src
              # Move the $GOPATH/src contents into /.vendor
              mv  $GOPATH/src ./vendor
          fi
        cd ..

        mkdir -pv build

        # TAR everything up...
        OUTPUT_FILE="./build/simple-go-webapp-source-$SEM_NUMBER.tgz"
        tar -zcf $OUTPUT_FILE --exclude=".git" ./simple-go-webapp-source

  - UNIT_TEST_SCRIPT: &UNIT_TEST_SCRIPT |
      tar -xf ./SourceArchive/*.tgz
      mv ./simple-go-webapp-source $GOPATH/src
      cd  $GOPATH/src/simple-go-webapp-source/app
      go test -v .

  - BUILD_SCRIPT: &BUILD_SCRIPT |
      cd app-version
        SEM_NUMBER=`cat number`
        SEM_VERSION=`cat version`
        echo "SEM_NUMBER=$SEM_NUMBER, SEM_VERSION=$SEM_VERSION"
      cd ..

      tar -xf ./SourceArchive/*.tgz
      mv ./simple-go-webapp-source $GOPATH/src
      pushd $GOPATH/src/simple-go-webapp-source/app
      go build -o app .
      popd
      OUTPUT_FILE="./build/simple-go-webapp-app-$SEM_NUMBER"
      cp $GOPATH/src/simple-go-webapp-source/app/app $OUTPUT_FILE

  - DOCKER_SETUP_SCRIPT: &DOCKER_SETUP_SCRIPT |
      cd BinaryArchive
        SEM_VERSION=`cat version`
        echo "SEM_VERSION=$SEM_VERSION"
      cd ..
      cp BinaryArchive/simple-go-webapp-app-$SEM_VERSION dockerbuild/simple-go-webapp-app
      cp -var simple-go-docker-source/docker/* dockerbuild
      ls -la dockerbuild
