groups: []
resources:
- name: version
  type: semver
  source:
    branch: version
    driver: git
    file: version
    initial_version: 0.0.1
    password: {{git-password}}
    uri: https://github.com/tryggth/concourse-example.git
    username: tryggth
- name: my-repo
  type: git
  source:
    uri: https://github.com/tryggth/concourse-example.git
- name: hello-world-docker-image
  type: docker-image
  source:
    email: tryggth2009@gmail.com
    password: {{git-key}}
    repository: tryggth/hello-world
    username: tryggth
resource_types: []
jobs:
- name: job-build-go
  plan:
    - get: my-repo
      trigger: true
    - task: task-build
      file: my-repo/ci/tasks/task-build.yml
- name: job-publish
  public: true
  serial: true
  plan:
  - get: version
    params:
      bump: minor
  - get: my-repo
    trigger: true
  - put: hello-world-docker-image
    params:
      build: my-repo
      tag: version/version
  - put: version
    params:
      file: version/version
