---
jobs:
- name: run-tests
  public: true
  serial: true
  plan:
  - get: simple-go-webapp-source
    trigger: true
  - task: run-build
    file: simple-go-webapp/ci/build.yml
#  - put: deploy-web-app
#    params:
#      manifest: simple-go-webapp/manifest.yml
#      path: simple-go-webapp/

resources:
- name: simple-go-webapp-source
  type: git
  source:
    uri: https://github.com/tryggth/concourse-example
    paths: [app/*]

#- name: deploy-web-app
#  type: cf
#  source:
#    api: https://api.run.pivotal.io
#    username: {cf-user}
#    password: {cf-password}
#    organization: {cf-org}
#    space: {cf-space}
#    skip_cert_check: false
